spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/game_meta
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

riot.api.key=${RIOT_API_KEY}
riot.account.base-url=https://asia.api.riotgames.com

# Google OAuth2
# Google Cloud Console redirect URI:
# http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
