spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/game_meta
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

riot.api.key=${RIOT_API_KEY}
riot.account.base-url=https://asia.api.riotgames.com

# Google OAuth2
# Google Cloud Console redirect URI:
# http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Riot Match-V5는 KR 기준 asia regional route 사용
riot.match.base-url=https://asia.api.riotgames.com

# Personal key는 100 requests / 2 minutes 제한이 있으므로 안전하게 천천히 호출
riot.request-delay-ms=1300

# Auto Riot Data Collection
riot.auto-collect.enabled=true

# 한 유저당 최근 몇 경기 가져올지
riot.auto-collect.match-count-per-player=10

# 한 사이클에서 처리할 유저 수
riot.auto-collect.max-players-per-cycle=5

# 유저 1명 수집 끝나고 다음 유저로 넘어가기 전 대기
riot.auto-collect.delay-between-players-ms=5000

# 한 사이클 끝난 뒤 다음 사이클까지 대기 시간
# 5분
riot.auto-collect.fixed-delay-ms=300000

# Riot Ranking API
riot.platform.base-url=https://kr.api.riotgames.com
riot.account.base-url=https://asia.api.riotgames.com

# 랭킹 100명 Riot ID 변환 시 API 제한 방지용 대기 시간
riot.ranking.account-delay-ms=1400

# 랭킹 유저 전적 수집 시 유저 사이 대기 시간
riot.ranking.collect-delay-ms=3000

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=${GEMINI_MODEL:gemini-3.5-flash}
